// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppGSL.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mlogLk_Rcpp
double mlogLk_Rcpp(arma::mat allprobs, arma::mat egamma, arma::rowvec foo, int n);
RcppExport SEXP _holtz_mlogLk_Rcpp(SEXP allprobsSEXP, SEXP egammaSEXP, SEXP fooSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type allprobs(allprobsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type egamma(egammaSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type foo(fooSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(mlogLk_Rcpp(allprobs, egamma, foo, n));
    return rcpp_result_gen;
END_RCPP
}
// pdf_n
NumericVector pdf_n(NumericVector y);
RcppExport SEXP _holtz_pdf_n(SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(pdf_n(y));
    return rcpp_result_gen;
END_RCPP
}
// pdf_s
NumericVector pdf_s(NumericVector y, double nu);
RcppExport SEXP _holtz_pdf_s(SEXP ySEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(pdf_s(y, nu));
    return rcpp_result_gen;
END_RCPP
}
// pdf_t
NumericVector pdf_t(NumericVector y, double df);
RcppExport SEXP _holtz_pdf_t(SEXP ySEXP, SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(pdf_t(y, df));
    return rcpp_result_gen;
END_RCPP
}
// pdf_vg
NumericVector pdf_vg(NumericVector y, double nu);
RcppExport SEXP _holtz_pdf_vg(SEXP ySEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(pdf_vg(y, nu));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_holtz_mlogLk_Rcpp", (DL_FUNC) &_holtz_mlogLk_Rcpp, 4},
    {"_holtz_pdf_n", (DL_FUNC) &_holtz_pdf_n, 1},
    {"_holtz_pdf_s", (DL_FUNC) &_holtz_pdf_s, 2},
    {"_holtz_pdf_t", (DL_FUNC) &_holtz_pdf_t, 2},
    {"_holtz_pdf_vg", (DL_FUNC) &_holtz_pdf_vg, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_holtz(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
